//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Factory> Factories { get; set; }
        public virtual DbSet<Guest> Guests { get; set; }
        public virtual DbSet<mange> manges { get; set; }
        public virtual DbSet<Order1> Order1 { get; set; }
        public virtual DbSet<OrReject> OrRejects { get; set; }
        public virtual DbSet<pay> pays { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Repertory> Repertories { get; set; }
        public virtual DbSet<salary> salaries { get; set; }
        public virtual DbSet<Sell> Sells { get; set; }
        public virtual DbSet<Sell_Reject> Sell_Reject { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
    }
}
