//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factory
    {
        public string 供应商编号 { get; set; }
        public string 供应商名称 { get; set; }
        public string 联系人 { get; set; }
        public string 联系电话 { get; set; }
        public string 供应商地址 { get; set; }
    }
}
