//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class pay
    {
        public string 结算号 { get; set; }
        public string 结算账户 { get; set; }
        public Nullable<decimal> 付款金额 { get; set; }
        public string 结算方式 { get; set; }
    }
}
