//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string 商品编号 { get; set; }
        public string 商品名称 { get; set; }
        public double 商品单价 { get; set; }
        public double 零售价 { get; set; }
        public string 联系地址 { get; set; }
        public string 当前库存 { get; set; }
    }
}
