//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sell_Reject
    {
        public string 订单编号 { get; set; }
        public string 商品名称 { get; set; }
        public decimal 退货数量 { get; set; }
        public string 退货日期 { get; set; }
        public string 客户编号 { get; set; }
        public string 客户名称 { get; set; }
        public string 所属仓库 { get; set; }
        public Nullable<decimal> 应退款金额 { get; set; }
    }
}
